services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEBUG=1
      - CLEAN_TMPDIR=false
      - LOCALSTACK_TMP_DIR=/tmp/localstack_tmpdir
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "localstack_tmp:/tmp/localstack_tmpdir"

volumes:
  localstack_tmp:
